#ifndef ANTPLUS_BICYCLEPOWERPROFILEPRIVATEDEFINES_h
#define ANTPLUS_BICYCLEPOWERPROFILEPRIVATEDEFINES_h

#include <Profiles/BicyclePower/ANTPLUS_BicyclePowerDefines.h>

/* Channel Config */
#define CHANNELPERIOD                          8182
// 30 / 2.5 = 12
#define SEARCHTIMEOUT                          12

#define GENERALCALIBRATION_NUMBER     								0x01
#define STANDARDPOWERONLY_NUMBER 											0x10
#define STANDARDWHEELTORQUE_NUMBER 										0x11
#define STANDARDCRANKTORQUE_NUMBER 										0x12
#define TORQUEEFFECTIVENESSANDPEDALSMOOTHNESS_NUMBER 	0x13
#define CRANKTORQUEFREQUENCY_NUMBER 									0x20

/* Fixed Bytes */

#endif // ANTPLUS_BICYCLEPOWERPROFILEPRIVATEDEFINES_h
