#ifndef ANTPLUS_BICYCLEPOWERPROFILEDEFINES_h
#define ANTPLUS_BICYCLEPOWERPROFILEDEFINES_h

#define ANTPLUS_BICYCLEPOWER_DEVICETYPE 11

/* Sensor Types */
#define BICYCLEPOWER_FLAGS_SENSORTYPE_POWERONLY       0
#define BICYCLEPOWER_FLAGS_SENSORTYPE_TORQUEWHEEL 		1
#define BICYCLEPOWER_FLAGS_SENSORTYPE_TORQUECRANK 		2
#define BICYCLEPOWER_FLAGS_SENSORTYPE_CTF          		3

#endif // ANTPLUS_BICYCLEPOWERPROFILEDEFINES_h
