#ifndef ANTPLUS_PROFILEBICYCLEPOWERDATAPAGES_h
#define ANTPLUS_PROFILEBICYCLEPOWERDATAPAGES_h

#include <Profiles/BicyclePower/DataPages/ANTPLUS_BicyclePowerStandardPowerOnly.h>
#include <Profiles/BicyclePower/DataPages/ANTPLUS_BicyclePowerStandardWheelTorque.h>
#include <Profiles/BicyclePower/DataPages/ANTPLUS_BicyclePowerStandardCrankTorque.h>
#include <Profiles/BicyclePower/DataPages/ANTPLUS_BicyclePowerTorqueEffectivenessAndPedalSmoothness.h>

#endif // ANTPLUS_PROFILEBICYCLEPOWERDATAPAGES_h
