#ifndef ANTPLUS_BICYCLEPOWERPROFILEDEFINES_h
#define ANTPLUS_BICYCLEPOWERPROFILEDEFINES_h

#define ANTPLUS_BICYCLEPOWER_DEVICETYPE 11

/* Sensor Types */
#define ANTPLUS_BICYCLEPOWER_FLAGS_SENSORTYPE_POWERONLY       0
#define ANTPLUS_BICYCLEPOWER_FLAGS_SENSORTYPE_TORQUEWHEEL 		1
#define ANTPLUS_BICYCLEPOWER_FLAGS_SENSORTYPE_TORQUECRANK 		2
#define ANTPLUS_BICYCLEPOWER_FLAGS_SENSORTYPE_CTF          		3

/* DataPage Defines */
#define ANTPLUS_BICYCLEPOWER_DATAPAGES_STANDARDPOWERONLY_PEDALPOWER_NOTUSED 0xFF
#define ANTPLUS_BICYCLEPOWER_DATAPAGES_STANDARDPOWERONLY_INSTANTANEOUSCADENCE_INVALID 0xFF

#endif // ANTPLUS_BICYCLEPOWERPROFILEDEFINES_h
