#ifndef ANTPLUS_BICYCLEPOWERPROFILEPRIVATEDEFINES_h
#define ANTPLUS_BICYCLEPOWERPROFILEPRIVATEDEFINES_h

#include <Profiles/BicyclePower/ANTPLUS_BicyclePowerDefines.h>

/* Channel Config */
#define ANTPLUS_BICYCLEPOWER_DISPLAY_CHANNELTYPE 										CHANNEL_TYPE_BIDIRECTIONAL_RECEIVE
#define ANTPLUS_BICYCLEPOWER_SENSOR_CHANNELTYPE                     CHANNEL_TYPE_BIDIRECTIONAL_TRANSMIT
#define ANTPLUS_BICYCLEPOWER_DEVICETYPE                             11
#define ANTPLUS_BICYCLEPOWER_CHANNELPERIOD                          8182
// 30 / 2.5 = 12
#define ANTPLUS_BICYCLEPOWER_SEARCHTIMEOUT                          12

/* Fixed Bytes */
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_DATAPAGE_BYTE                 0
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_UPDATEEVENTCOUNT_BYTE         1

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_GENERALCALIBRATION_NUMBER     0x01
/* Power Only Main Data Page */
/* DataPage for Power Only, CTF does not need to support.
 * Note: Currently not writing any of this with CTF in mind.
 * CTF support needs to be added (not in scope for my project.
 */
/* Standard Power-Only */
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDPOWERONLY_NUMBER 0x10

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDPOWERONLY_UPDATEEVENTCOUNT_BYTE   1
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDPOWERONLY_PEDALPOWER_BYTE 2
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDPOWERONLY_INSTANTANEOUSCADENCE_BYTE 3
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDPOWERONLY_ACCUMULATEDPOWER_LSB_BYTE 4
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDPOWERONLY_ACCUMULATEDPOWER_MSB_BYTE 5
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDPOWERONLY_INSTANTANEOUSPOWER_LSB_BYTE 6
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDPOWERONLY_INSTANTANEOUSPOWER_MSB_BYTE 7

/* Wheel Torque Main Data Page */

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDWHEELTORQUE_NUMBER 0x11

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_WHEELTICKS_WHEELTORQUE_BYTE                   2
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_CADENCE_WHEELTORQUE_BYTE                      3
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_WHEELPERIODLSB_WHEELTORQUE_BYTE               4
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_WHEELPERIODMSB_WHEELTORQUE_BYTE               5
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_ACCUMULATEDTORQUELSB_WHEELTORQUE_BYTE         6
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_ACCUMULATEDTORQUEMSB_WHEELTORQUE_BYTE         7

/* Standard Crank Torque Main Data Page */

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_STANDARDCRANKTORQUE_NUMBER 0x12

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_CRANKTICKS_CRANKTORQUE_BYTE                   2
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_CADENCE_CRANKTORQUE_BYTE                      3
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_CRANKPERIODLSB_CRANKTORQUE_BYTE               4
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_CRANKPERIODMSB_CRANKTORQUE_BYTE               5
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_ACCUMULATEDTORQUELSB_CRANKTORQUE_BYTE         6
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_ACCUMULATEDTORQUEMSB_CRANKTORQUE_BYTE         7

/* Pedal Smoothness Main Data Page */

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_TORQUEEFFECTIVENESSANDPEDALSMOOTHNESS_NUMBER 0x13

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_LEFTEFFECTIVENESS_PEDALSMOOTHNESS_BYTE        2
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_RIGHTEFFECTIVENESS_PEDALSMOOTHNESS_BYTE       3
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_LEFTSMOOTHNESS_PEDALSMOOTHNESS_BYTE           4
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_RIGHTSMOOTHNESS_PEDALSMOOTHNESS_BYTE          5

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_CRANKTORQUEFREQUENCY_NUMBER 0x20
/* Crank Torque Frequency Main Data Page

NOTE: CTF messages are big endian. The byte order for multi-byte
fields in these messages is reversed with respect to standard ANT+ messages

Not implemented.
*/

/*
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_DATAPAGE_CTF_NUMBER                       0x20

#define ANTPLUS_BICYCLEPOWER_DATAPAGE_SLOPEMSB_CTF_BYTE                             2
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_SLOPELSB_CTF_BYTE                             3
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_TIMESTAMPMSB_CTF_BYTE                         4
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_TIMESTAMPLSB_CTF_BYTE                         5
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_TORQUETICKSTAMPMSB_CTF_BYTE                   6
#define ANTPLUS_BICYCLEPOWER_DATAPAGE_TORQUETICKSTAMPLSB_CTF_BYTE                   7
*/

#endif // ANTPLUS_BICYCLEPOWERPROFILEPRIVATEDEFINES_h
