#ifndef ANTPLUS_HEARTRATEPROFILEPRIVATEDEFINES_h
#define ANTPLUS_HEARTRATEPROFILEPRIVATEDEFINES_h

/* Channel Config */
#define ANTPLUS_HEARTRATE_CHANNELPERIOD 8070
// 30 / 2.5 = 12
#define ANTPLUS_HEARTRATE_SEARCHTIMEOUT 12

/* DataPage Numbers */
#define DEFAULT_NUMBER 0
#define CUMULATIVEOPERATINGTIME_NUMBER 1
#define MANUFACTURERINFORMATION_NUMBER 2
#define PRODUCTINFORMATION_NUMBER 3
#define PREVIOUSHEARTBEAT_NUMBER 4
#define SWIMINTERVALSUMMARY_NUMBER 5
#define CAPABILITIES_NUMBER 6
#define BATTERYSTATUS_NUMBER 7

#endif // ANTPLUS_HEARTRATEPROFILEPRIVATEDEFINES_h
