#ifndef ANTPLUS_HEARTRATEPROFILEPRIVATEDEFINES_h
#define ANTPLUS_HEARTRATEPROFILEPRIVATEDEFINES_h

/* Channel Config */
#define ANTPLUS_HEARTRATE_CHANNELPERIOD 8070
// 30 / 2.5 = 12
#define ANTPLUS_HEARTRATE_SEARCHTIMEOUT 12

/* DataPage Numbers */
#define HEARTRATE_DEFAULT_NUMBER 0
#define HEARTRATE_CUMULATIVEOPERATINGTIME_NUMBER 1
#define HEARTRATE_MANUFACTURERINFORMATION_NUMBER 2
#define HEARTRATE_PRODUCTINFORMATION_NUMBER 3
#define HEARTRATE_PREVIOUSHEARTBEAT_NUMBER 4
#define HEARTRATE_SWIMINTERVALSUMMARY_NUMBER 5
#define HEARTRATE_CAPABILITIES_NUMBER 6
#define HEARTRATE_BATTERYSTATUS_NUMBER 7

#endif // ANTPLUS_HEARTRATEPROFILEPRIVATEDEFINES_h
