#ifndef ANTPLUS_HEARTRATEPROFILEDEFINES_h
#define ANTPLUS_HEARTRATEPROFILEDEFINES_h

#define ANTPLUS_HEARTRATE_DEVICETYPE 120

#define ANTPLUS_HEARTRATE_DATAPAGE_CAPABILITIES_FEATURES_EXTENDEDRUNNING  0x01
#define ANTPLUS_HEARTRATE_DATAPAGE_CAPABILITIES_FEATURES_EXTENDEDCYCLING  0x02
#define ANTPLUS_HEARTRATE_DATAPAGE_CAPABILITIES_FEATURES_EXTENDEDSWIMMING 0x04
#define ANTPLUS_HEARTRATE_DATAPAGE_CAPABILITIES_FEATURES_MANUFACTURER1    0x40
#define ANTPLUS_HEARTRATE_DATAPAGE_CAPABILITIES_FEATURES_MANUFACTURER2    0x80

#define ANTPLUS_HEARTRATE_FLAGS_CUMULATIVEOPERATINGTIME_SUPPORTED (1 << 0)
#define ANTPLUS_HEARTRATE_FLAGS_PREVIOUSHEARTBEAT_SUPPORTED       (1 << 1)
#define ANTPLUS_HEARTRATE_FLAGS_EXTENTED_FEATURES                 (1 << 2)
#define ANTPLUS_HEARTRATE_FLAGS_BATTERYSTATUS_SUPPORTED           (1 << 3)


#endif // ANTPLUS_HEARTRATEPROFILEDEFINES_h
