#ifndef ANTPLUS_SHIFTINGPROFILEPRIVATEDEFINES_h
#define ANTPLUS_SHIFTINGPROFILEPRIVATEDEFINES_h

/* Channel Config */
#define SHIFTING_CHANNELPERIOD 8192
// 30 / 2.5 = 12
#define SHIFTING_SEARCHTIMEOUT 12

// Transmission pattern math
#define ANTPLUS_SHIFTING_BACKGROUNDPAGE_INTERLEAVEINTERVAL 260
#define ANTPLUS_SHIFTING_NUMBERBACKGROUNDPAGES_PERCOMPONENT 3

/* Pages */
#define ANTPLUS_SHIFTING_DATAPAGE_SHIFTSYSTEMSTATUS_NUMBER 1

// Base page */
#define ANTPLUS_SHIFTING_DATAPAGEBASE_DATAPAGE_BYTE 0x00

#endif // ANTPLUS_SHIFTINGPROFILEPRIVATEDEFINES_h
