#ifndef ANTPLUS_SHIFTINGPROFILEPRIVATEDEFINES_h
#define ANTPLUS_SHIFTINGPROFILEPRIVATEDEFINES_h

/* Channel Config */
#define ANTPLUS_SHIFTING_CHANNELTYPE CHANNEL_TYPE_BIDIRECTIONAL_RECEIVE 
#define ANTPLUS_SHIFTING_DEVICETYPE 34
#define ANTPLUS_SHIFTING_CHANNELPERIOD 8192
// Master channel
#define ANTPLUS_SHIFTING_MASTER_CHANNELTYPE 0x10 
#define ANTPLUS_SHIFTING_MASTER_TRANSMISSIONTYPE 5
#define ANTPLUS_SHIFTING_MASTER_DEVICENUMBER 5

// 30 / 2.5 = 12
#define ANTPLUS_SHIFTING_SEARCHTIMEOUT 12

/* Pages */
#define ANTPLUS_SHIFTING_DATAPAGE_SHIFTSYSTEMSTATUS 1

// Base page */
#define ANTPLUS_SHIFTING_DATAPAGEBASE_DATAPAGE_BYTE 0x00


#endif // ANTPLUS_SHIFTINGPROFILEPRIVATEDEFINES_h
