#ifndef ANTPLUS_SHIFTINGPROFILEDEFINES_h
#define ANTPLUS_SHIFTINGPROFILEDEFINES_h

#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_SYSTEM 0
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_FRONTDERAILLEUR 1
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_REARDERAILLEUR 2
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_LEFTSHIFTER 3
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_RIGHTSHIFTER 4
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_SHIFTER 5
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_LEFTEXTENSIONSHIFTER 6
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_RIGHTEXTENSIONSHIFTER 7
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_EXTENSIONSHIFTER1 8
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_LEFTEXTENSIONSHIFTER2 9
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_RIGHTEXTENSIONSHIFTER2 10
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_EXTENSIONSHIFTER2 11
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_UNKNOWNIDENTIFIED 15

#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_SYSTEM_FLAG (1 << 0)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_FRONTDERAILLEUR_FLAG (1 << 1)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_REARDERAILLEUR_FLAG (1 << 2)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_LEFTSHIFTER_FLAG (1 << 3)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_RIGHTSHIFTER_FLAG (1 << 4)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_SHIFTER_FLAG (1 << 5)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_LEFTEXTENSIONSHIFTER_FLAG (1 << 6)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_RIGHTEXTENSIONSHIFTER_FLAG (1 << 7)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_EXTENSIONSHIFTER1_FLAG (1 << 8)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_LEFTEXTENSIONSHIFTER2_FLAG (1 << 9)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_RIGHTEXTENSIONSHIFTER2_FLAG (1 << 10)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_EXTENSIONSHIFTER2_FLAG (1 << 11)
#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_UNKNOWNIDENTIFIED_FLAG (1 << 15)

#define ANTPLUS_SHIFTING_COMPONENTIDENTIFIER_NOTUSED 0xFF

#endif // ANTPLUS_SHIFTINGPROFILEDEFINES_h
