#ifndef ANTPLUS_BICYCLESPEEDPROFILEPRIVATEDEFINES_h
#define ANTPLUS_BICYCLESPEEDPROFILEPRIVATEDEFINES_h

#include <Profiles/BicycleSpeed/ANTPLUS_BicycleSpeedDefines.h>

/* Channel Config */
#define BICYCLESPEED_CHANNELPERIOD 8118
// 30 / 2.5 = 12
#define BICYCLESPEED_SEARCHTIMEOUT 12

#define BICYCLESPEED_DEFAULT_NUMBER 0
#define BICYCLESPEED_CUMULATIVEOPERATINGTIME_NUMBER 1
#define BICYCLESPEED_MANUFACTURERID_NUMBER 2
#define BICYCLESPEED_PRODUCTID_NUMBER 3
#define BICYCLESPEED_BATTERYSTATUS_NUMBER 4
#define BICYCLESPEED_MOTIONANDSPEED_NUMBER 5

#endif // ANTPLUS_BICYCLESPEEDPROFILEPRIVATEDEFINES_h
