#ifndef ANTPLUS_BICYCLESPEEDPROFILEPRIVATEDEFINES_h
#define ANTPLUS_BICYCLESPEEDPROFILEPRIVATEDEFINES_h

#include <Profiles/BicycleSpeed/ANTPLUS_BicycleSpeedDefines.h>

/* Channel Config */
#define BICYCLESPEED_CHANNELPERIOD 8118
// 30 / 2.5 = 12
#define BICYCLESPEED_SEARCHTIMEOUT 12

#endif // ANTPLUS_BICYCLESPEEDPROFILEPRIVATEDEFINES_h
