#include <Profiles/Lev/DataPages/ANTPLUS_LevCapabilities.h>
#include <Profiles/Lev/ANTPLUS_LevPrivateDefines.h>

LevCapabilities::LevCapabilities(AntRxDataResponse& dp) :
    LevBaseMainDataPage(dp) {}

uint8_t LevCapabilities::getNumberOfAssistModesSupported() {
    return (getData(ANTPLUS_LEV_DATAPAGE_LEVCAPABILITIES_TRAVELMODESSUPPORTED_BYTE) & ANTPLUS_LEV_DATAPAGE_LEVCAPABILITIES_TRAVELMODESSUPPORTED_NUMBERASSISTMODES_MASK) >> ANTPLUS_LEV_DATAPAGE_LEVCAPABILITIES_TRAVELMODESSUPPORTED_NUMBERASSISTMODES_SHIFT;
}

uint8_t LevCapabilities::getNumberOfRegenerativeModesSupported() {
    return getData(ANTPLUS_LEV_DATAPAGE_LEVCAPABILITIES_TRAVELMODESSUPPORTED_BYTE) & ANTPLUS_LEV_DATAPAGE_LEVCAPABILITIES_TRAVELMODESSUPPORTED_NUMBERREGENERATIVEMODES_MASK;
}

uint16_t LevCapabilities::getWheelCircumference() {
    return (uint16_t)getData(ANTPLUS_LEV_DATAPAGE_LEVCAPABILITIES_WHEELCIRCUMFERENCE_LSB_BYTE) + (((uint16_t)getData(ANTPLUS_LEV_DATAPAGE_LEVCAPABILITIES_WHEELCIRCUMFERENCE_MSB_BYTE) & ANTPLUS_LEV_DATAPAGE_LEVCAPABILITIES_WHEELCIRCUMFERENCE_MSB_MASK) << ANTPLUS_LEV_DATAPAGE_LEVCAPABILITIES_WHEELCIRCUMFERENCE_MSB_SHIFT);
}
