#ifndef ANTPLUS_FECPROFILEDEFINES_h
#define ANTPLUS_FECPROFILEDEFINES_h

#define ANTPLUS_FEC_REALTIMECHANNEL_DEVICETYPE 17
// TODO there are multiple device types for this profile

#define ANTPLUS_FEC_DATAPAGE_FECAPABILITIES_CAPABILITIESBITFIELD_SUPPORTSBASICRESISTANCEMODE  (1 << 0)
#define ANTPLUS_FEC_DATAPAGE_FECAPABILITIES_CAPABILITIESBITFIELD_SUPPORTSTARGETPOWERMODE  		(1 << 1)
#define ANTPLUS_FEC_DATAPAGE_FECAPABILITIES_CAPABILITIESBITFIELD_SUPPORTSSIMULATIONMODE  			(1 << 2)

#endif // ANTPLUS_FECPROFILEDEFINES_h
