#ifndef ANTPLUS_FECPROFILEDEFINES_h
#define ANTPLUS_FECPROFILEDEFINES_h

#define ANTPLUS_FEC_REALTIMECHANNEL_DEVICETYPE 17
// TODO there are multiple device types for this profile

#define ANTPLUS_FEC_DATAPAGE_GENERALFEDATA_EQUIPMENTTYPEBITFIELD_GENERAL 				16
#define ANTPLUS_FEC_DATAPAGE_GENERALFEDATA_EQUIPMENTTYPEBITFIELD_TREADMILL 			19
#define ANTPLUS_FEC_DATAPAGE_GENERALFEDATA_EQUIPMENTTYPEBITFIELD_ELLIPTICAL			20
#define ANTPLUS_FEC_DATAPAGE_GENERALFEDATA_EQUIPMENTTYPEBITFIELD_STATIONARYBIKE	21
#define ANTPLUS_FEC_DATAPAGE_GENERALFEDATA_EQUIPMENTTYPEBITFIELD_ROWER					22
#define ANTPLUS_FEC_DATAPAGE_GENERALFEDATA_EQUIPMENTTYPEBITFIELD_CLIMBER				23
#define ANTPLUS_FEC_DATAPAGE_GENERALFEDATA_EQUIPMENTTYPEBITFIELD_NORDICSKIER		24
#define ANTPLUS_FEC_DATAPAGE_GENERALFEDATA_EQUIPMENTTYPEBITFIELD_TRAINER				25

#define ANTPLUS_FEC_DATAPAGE_FECAPABILITIES_CAPABILITIESBITFIELD_SUPPORTSBASICRESISTANCEMODE  (1 << 0)
#define ANTPLUS_FEC_DATAPAGE_FECAPABILITIES_CAPABILITIESBITFIELD_SUPPORTSTARGETPOWERMODE  		(1 << 1)
#define ANTPLUS_FEC_DATAPAGE_FECAPABILITIES_CAPABILITIESBITFIELD_SUPPORTSSIMULATIONMODE  			(1 << 2)

#endif // ANTPLUS_FECPROFILEDEFINES_h
