#ifndef ANTPLUS_FECPROFILEPRIVATEDEFINES_h
#define ANTPLUS_FECPROFILEPRIVATEDEFINES_h

/* Channel Config */
#define ANTPLUS_FEC_DISPLAY_CHANNELTYPE CHANNEL_TYPE_BIDIRECTIONAL_RECEIVE
#define ANTPLUS_FEC_MONITOR_CHANNELTYPE CHANNEL_TYPE_BIDIRECTIONAL_TRANSMIT
#define ANTPLUS_FEC_CHANNELPERIOD 8192
// 30 / 2.5 = 12
#define ANTPLUS_FEC_SEARCHTIMEOUT 12

/* General Main DataPage */
#define ANTPLUS_FEC_DATAPAGE_GENERAL_MAIN_DATAPAGE_BYTE 0
#define ANTPLUS_FEC_DATAPAGE_GENERAL_MAIN_EQUIPMENT_TYPE_BIT_BYTE 1
#define ANTPLUS_FEC_DATAPAGE_GENERAL_MAIN_ELAPSED_TIME_BYTE 2
#define ANTPLUS_FEC_DATAPAGE_GENERAL_MAIN_DISTANCE_TRAVELED_BYTE 3
#define ANTPLUS_FEC_DATAPAGE_GENERAL_MAIN_SPEED_LSB_BYTE 4
#define ANTPLUS_FEC_DATAPAGE_GENERAL_MAIN_SPEED_MSB_BYTE 5
#define ANTPLUS_FEC_DATAPAGE_GENERAL_MAIN_HEARTRATE_BYTE 6
#define ANTPLUS_FEC_DATAPAGE_GENERAL_MAIN_CAPBILITY_FESTATE_BIT_BYTE 7

/* FE Main DataPage */
#define ANTPLUS_FEC_DATAPAGE_FE_MAIN_DATAPAGE_BYTE 0
#define ANTPLUS_FEC_DATAPAGE_FE_MAIN_CADENCE_BYTE 4
#define ANTPLUS_FEC_DATAPAGE_FE_MAIN_NEGTIVE_VERTICAL_DISTANCE_BYTE 5

/* Trainer Data DataPage */
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_DATAPAGE_BYTE 0
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_UPDATE_EVENT_COUNT_BYTE 1
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_INSTANTANEOUS_CADENCE_BYTE 2
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_ACCUMULATED_POWER_LSB_BYTE 3
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_ACCUMULATED_POWER_MSB_BYTE 4
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_INSTANTANEOUS_POWER_LSB_BYTE 5
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_INSTANTANEOUS_POWER_MSB_BYTE 6
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_TRAINER_STATUS_BYTE 6
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_FLAGS_FESTATE_BIT_BYTE 7

/* Default DataPage */
#define ANTPLUS_FEC_DATAPAGE_DEFAULT_NUMBER 0
#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_NUMBER 25

#endif // ANTPLUS_FECPROFILEPRIVATEDEFINES_h
