#ifndef ANTPLUS_FECPROFILEPRIVATEDEFINES_h
#define ANTPLUS_FECPROFILEPRIVATEDEFINES_h

#include <Profiles/Fec/ANTPLUS_FecDefines.h>

/* Channel Config */
#define ANTPLUS_FEC_MONITOR_CHANNELTYPE CHANNEL_TYPE_BIDIRECTIONAL_TRANSMIT
#define ANTPLUS_FEC_CHANNELPERIOD 8192
// 30 / 2.5 = 12
#define ANTPLUS_FEC_SEARCHTIMEOUT 12

/* DataPages number */
#define GENERAL_FE_DATA_NUMBER 16
#define GENERAL_SETTINGS_PAGE_NUMBER 17
#define SPECIFIC_TRAINER_DATA_NUMBER 25
#define BASIC_RESISTANCE_NUMBER 48
#define TARGET_POWER_NUMBER 49
#define TRACK_RESISTANCE_NUMBER 51
#define FE_CAPABILITIES_NUMBER 54
#define USER_CONFIGURATION_NUMBER 55

#endif // ANTPLUS_FECPROFILEPRIVATEDEFINES_h
