#ifndef ANTPLUS_LEVPROFILEPRIVATEDEFINES_h
#define ANTPLUS_LEVPROFILEPRIVATEDEFINES_h

/* Channel Config */
#define LEV_CHANNELPERIOD 8192
// 30 / 2.5 = 12
#define LEV_SEARCHTIMEOUT 12

#endif // ANTPLUS_BICYCLESPEEDPROFILEPRIVATEDEFINES_h
