#ifndef ANTPLUS_LEVPROFILEPRIVATEDEFINES_h
#define ANTPLUS_LEVPROFILEPRIVATEDEFINES_h

/* Channel Config */
#define LEV_CHANNELPERIOD 8192
// 30 / 2.5 = 12
#define LEV_SEARCHTIMEOUT 12

#define SPEEDSYSTEMINFORMATION1_NUMBER                    1
#define SPEEDDISTANCEINFORMATION_NUMBER                   2
#define ALTSPEEDDISTANCEINFORMATION_NUMBER                34
#define SPEEDSYSTEMINFORMATION2_NUMBER                    3
#define BATTERYINFORMATION_NUMBER                         4
#define LEVCAPABILITIES_NUMBER                            5
#define DISPLAYDATA_NUMBER                         16

#endif // ANTPLUS_BICYCLESPEEDPROFILEPRIVATEDEFINES_h
