#ifndef ANTPLUS_COMMONDATAPAGEDEFINES_h
#define ANTPLUS_COMMONDATAPAGEDEFINES_h

/* Mode Settings */
#define ANTPLUS_COMMON_DATAPAGE_MODESETTINGS_SPORTSMODE_BYTE     7
#define ANTPLUS_COMMON_DATAPAGE_MODESETTINGS_SPORTSMODE_RUNNING  1
#define ANTPLUS_COMMON_DATAPAGE_MODESETTINGS_SPORTSMODE_CYCLING  2
#define ANTPLUS_COMMON_DATAPAGE_MODESETTINGS_SPORTSMODE_SWIMMING 5

#endif // ANTPLUS_COMMONDATAPAGEDEFINES_h
