#ifndef ANTPLUS_COMMONDATAPAGEDEFINES_h
#define ANTPLUS_COMMONDATAPAGEDEFINES_h

/* Mode Settigns */
#define ANTPLUS_COMMON_DATAPAGE_MODESETTINGS_NUMBER 76

/* Request Data Page */
#define ANTPLUS_COMMON_DATAPAGE_REQUESTDATAPAGE_NUMBER 70

#endif // ANTPLUS_COMMONDATAPAGEDEFINES_h