#ifndef ANTPLUS_ENVIRONMENTPROFILEPRIVATEDEFINES_h
#define ANTPLUS_ENVIRONMENTPROFILEPRIVATEDEFINES_h

/* Channel Config */
#define ANTPLUS_ENVIRONMENT_CHANNELTYPE CHANNEL_TYPE_BIDIRECTIONAL_RECEIVE
#define ANTPLUS_ENVIRONMENT_DEVICETYPE 25
#define ANTPLUS_ENVIRONMENT_CHANNELPERIOD 8192
// 45 / 2.5 = 18
#define ANTPLUS_ENVIRONMENT_SEARCHTIMEOUT 18

/* Base DataPage */
#define ANTPLUS_ENVIRONMENT_DATAPAGEBASE_DATAPAGE_BYTE 0

/* Temperature DataPage */
#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_NUMBER 1

/* Event Count */
#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_EVENTCOUNT_BYTE 2

/* 24 Hour Low */
#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_24HOURLOW_MSB_BYTE 2
#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_24HOURLOW_LSB_BYTE 3

#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_24HOURLOW_MSB_MASK 0xF0

#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_24HOURLOW_MSB_SHIFT 4

/* 24 Hour High */
#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_24HOURHIGH_LSB_BYTE 4
#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_24HOURHIGH_MSB_BYTE 5

#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_24HOURHIGH_LSB_MASK 0x0F

#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_24HOURHIGH_MSB_SHIFT 4

/* Current Temp */
#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_CURRENTTEMP_LSB_BYTE 6
#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_CURRENTTEMP_MSB_BYTE 7

#define ANTPLUS_ENVIRONMENT_DATAPAGE_TEMPERATURE_CURRENTTEMP_MSB_SHIFT 8

#endif // ANTPLUS_ENVIRONMENTPROFILEPRIVATEDEFINES_h
