#ifndef ANTPLUS_ENVIRONMENTPROFILEPRIVATEDEFINES_h
#define ANTPLUS_ENVIRONMENTPROFILEPRIVATEDEFINES_h

#include <Profiles/Environment/ANTPLUS_EnvironmentDefines.h>

/* Channel Config */
#define ENVIRONMENT_CHANNELPERIOD 8192
// 45 / 2.5 = 18
#define ENVIRONMENT_SEARCHTIMEOUT 18

#endif // ANTPLUS_ENVIRONMENTPROFILEPRIVATEDEFINES_h
