#ifndef ANTPLUS_ENVIRONMENTPROFILEPRIVATEDEFINES_h
#define ANTPLUS_ENVIRONMENTPROFILEPRIVATEDEFINES_h

/* Channel Config */
#define ANTPLUS_ENVIRONMENT_CHANNELTYPE CHANNEL_TYPE_BIDIRECTIONAL_RECEIVE
#define ANTPLUS_ENVIRONMENT_DEVICETYPE 25
#define ANTPLUS_ENVIRONMENT_CHANNELPERIOD 8192
// 30 / 2.5 = 12
#define ANTPLUS_ENVIRONMENT_SEARCHTIMEOUT 45

/* Base DataPage */
#define ANTPLUS_ENVIRONMENT_DATAPAGEBASE_DATAPAGE_BYTE 0

#endif // ANTPLUS_ENVIRONMENTPROFILEPRIVATEDEFINES_h
