#ifndef ANTPLUS_DEFINES_h
#define ANTPLUS_DEFINES_h

// Misc
#define ANTPLUS_MAX_CHANNELS_POSSIBLE 15
#define ANTPLUS_NETWORKKEY_INDEX 0

// State
#define ANTPLUS_DRIVER_STATE_UNKNOWN 0

// Reset
#define ANTPLUS_RESET_NO_WAIT_FOR_STARTUP 0
#define ANTPLUS_RESET_WAIT_FOR_STARTUP 1

#endif // ANTPLUS_DEFINES_h