#ifndef ANTPLUS_PRIVATEDEFINES_h
#define ANTPLUS_PRIVATEDEFINES_h

#define ANTPLUS_TRANSMISSIONTYPE_LSN_MASK 0x0F
#define ANTPLUS_TRANSMISSION_SET_LSN(x, flags) ((x & ~ANTPLUS_TRANSMISSIONTYPE_LSN_MASK) | (ANTPLUS_TRANSMISSIONTYPE_LSN_MASK & flags))

/* Channel config stuff */
#define ANTPLUS_CHANNEL_FREQUENCY 57
#define ANTPLUS_DEVICENUMBER_WILDCARD 0
#define ANTPLUS_TRANSMISSIONTYPE_WILDCARD 0

#define ANTPLUS_DEFAULT_DATAPAGE_BYTE 0

#define ANTPLUS_DEFAULT_BYTE_MASK 0xFF

#define ANTPLUS_PAIRING_BIT_MASK 0x80

#define ANTPLUS_CHANNELEVENT_MESSAGECODE 1

#endif // ANTPLUS_PRIVATEDEFINES_h
