#ifndef ANTPLUS_PRIVATEDEFINES_h
#define ANTPLUS_PRIVATEDEFINES_h

#define ANTPLUS_CHANNEL_FREQUENCY 57

#define ANTPLUS_DEFAULT_DATAPAGE_BYTE 0

#define ANTPLUS_DEFAULT_BYTE_MASK 0xFF

#endif // ANTPLUS_PRIVATEDEFINES_h