#ifndef ANTPLUS_DEFINES_h
#define ANTPLUS_DEFINES_h

// Misc
#define ANTPLUS_MAX_CHANNELS_POSSIBLE 15
#define ANTPLUS_NETWORKKEY_INDEX 0
#define ANTPLUS_DRIVER_RESET_TIMEOUT 2000

// Errors
#define ANTPLUS_RESET_RADIO_FAILED 1

// State
#define ANTPLUS_DRIVER_STATE_UNKNOWN 0
#define ANTPLUS_DRIVER_STATE_STARTED 1

// Reset
#define ANTPLUS_RESET_NO_WAIT_FOR_STARTUP 0
#define ANTPLUS_RESET_WAIT_FOR_STARTUP 1

#endif // ANTPLUS_DEFINES_h