#ifndef ANTPLUS_FECPROFILEDEFINES_h
#define ANTPLUS_FECPROFILEDEFINES_h

#define ANTPLUS_FEC_DEVICETYPE 17

#define ANTPLUS_FEC_FLAGS_CUMULATIVEOPERATINGTIME_SUPPORTED (1 << 0)
#define ANTPLUS_FEC_FLAGS_PREVIOUSHEARTBEAT_SUPPORTED       (1 << 1)
#define ANTPLUS_FEC_FLAGS_EXTENTED_FEATURES                 (1 << 2)
#define ANTPLUS_FEC_FLAGS_BATTERYSTATUS_SUPPORTED           (1 << 3)

#define ANTPLUS_FEC_DATAPAGE_CAPABILITIES_FEATURES_EXTENDEDRUNNING  0x01
#define ANTPLUS_FEC_DATAPAGE_CAPABILITIES_FEATURES_EXTENDEDCYCLING  0x02
#define ANTPLUS_FEC_DATAPAGE_CAPABILITIES_FEATURES_EXTENDEDSWIMMING 0x04
#define ANTPLUS_FEC_DATAPAGE_CAPABILITIES_FEATURES_MANUFACTURER1    0x40
#define ANTPLUS_FEC_DATAPAGE_CAPABILITIES_FEATURES_MANUFACTURER2    0x80

// TODO all below defines need to be added to example
#define ANTPLUS_FEC_DATAPAGE_PREVIOUSHEARTBEAT_MANUFACTURERSPECIFIC_INVALID 0xFF

#define ANTPLUS_FEC_DATAPAGE_SWIMINTERVALSUMMARY_INTERVALAVERAGEFEC_INVALID 0
#define ANTPLUS_FEC_DATAPAGE_SWIMINTERVALSUMMARY_INTERVALMAXIMUMFEC_INVALID 0
#define ANTPLUS_FEC_DATAPAGE_SWIMINTERVALSUMMARY_SESSIONAVERAGEFEC_INVALID 0

#endif // ANTPLUS_FECPROFILEDEFINES_h
