#ifndef ANTPLUS_FECPROFILEPRIVATEDEFINES_h
#define ANTPLUS_FECPROFILEPRIVATEDEFINES_h

#include <Profiles/FitnessEquipmentControls/ANTPLUS_FitnessEquipmentControlsDefines.h>

/* Channel Config */
#define ANTPLUS_FEC_DISPLAY_CHANNELTYPE CHANNEL_TYPE_BIDIRECTIONAL_RECEIVE
#define ANTPLUS_FEC_MONITOR_CHANNELTYPE CHANNEL_TYPE_BIDIRECTIONAL_TRANSMIT
#define ANTPLUS_FEC_CHANNELPERIOD 8192
// 30 / 2.5 = 12
#define ANTPLUS_FEC_SEARCHTIMEOUT 12

#define ANTPLUS_FEC_DATAPAGE_TRAINER_DATA_NUMBER 25

#endif // ANTPLUS_FECPROFILEPRIVATEDEFINES_h
