#ifndef ANTPLUS_MUSCLEOXYGENPRIVATEDEFINES_h
#define ANTPLUS_MUSCLEOXYGENPRIVATEDEFINES_h

#include <Profiles/MuscleOxygen/ANTPLUS_MuscleOxygenDefines.h>

// Master channel
#define MUSCLEOXYGEN_CHANNELPERIOD 8192

// 30 / 2.5 = 12
#define MUSCLEOXYGEN_SEARCHTIMEOUT 12

/* Pages */
#define MUSCLEOXYGEN_MUSCLEOXYGENDATA_NUMBER 1
#define MUSCLEOXYGEN_COMMANDS_NUMBER 16

// Base page */
#define ANTPLUS_MUSCLEOXYGEN_DATAPAGEBASE_DATAPAGE_BYTE 0x00

#endif // ANTPLUS_MUSCLEOXYGENPRIVATEDEFINES_h
