#ifndef ANTPLUS_MUSCLEOXYGENPRIVATEDEFINES_h
#define ANTPLUS_MUSCLEOXYGENPRIVATEDEFINES_h

#include <Profiles/MuscleOxygen/ANTPLUS_MuscleOxygenDefines.h>

// Master channel
#define MUSCLEOXYGEN_CHANNELPERIOD 8192

// 30 / 2.5 = 12
#define MUSCLEOXYGEN_SEARCHTIMEOUT 12

#endif // ANTPLUS_MUSCLEOXYGENPRIVATEDEFINES_h
